spring:
    application: 
        name: fiap-tc5-ecommerce-session-ms
    data:
        mongodb:
            uri: ${MONGO_URL:mongodb://localhost:27017/fiap-tc5-ecommerce-session-ms}
server:
    port: 8085
    servlet:
        context-path: /ecommerce-management/api/v1
